# Generated by Django 3.1.7 on 2021-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='message',
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
